services:
  - type: web
    name: bloom-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 5000
      - key: TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
    healthCheckPath: /health
    disk:
      name: bloom-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
